### PR TITLE
add support SUPPORTS_ROOT_NS

### PR DESCRIPTION
**Pull request by InsaneTimeWatcher**
add support SUPPORTS_ROOT_NS , this work only with flag --force

### CODE REVIEW

**Comment by ross** [comment]
> add support SUPPORTS_ROOT_NS , this work only with flag --force

Can you elaborate. Why does it require `--force`?

**Comment by InsaneTimeWatcher** [comment]
> > add support SUPPORTS_ROOT_NS , this work only with flag --force
> 
> Can you elaborate. Why does it require `--force`?

Octodns by default required if change root ns
_octodns.provider.plan.RootNsChange: Root NS record change, force required_

**Review by ross — APPROVED** [review]
> Octodns by default required if change root ns

OK. Wasn't sure if you were meaning something else was requiring it.

**Comment by ross** [comment]
Looks like the addition fails all the tests. All the CI stuff can be run with the scripts under `./script`

**Comment by ross** [comment]
I don't have perms to push to the source branch and it's `main` so the normal flow is broken. Just going to re-close this and open a new PR with the change and test fixes.

**Pull request closed without merging**
